### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by V2dha** [MLH-Fellowship/Social-BERTerfly#19]
Below are the remaining tasks to be completed before the final demo :

- [x] Get the followering twitter handles and display it along with their personality type

- [x] Improve the UI of the dashboard. For instance - personality traits card is taking a lot of blank space and is looking uneven, remove the purchase banner if possible

- [x] Update the Readme with setting up code 

- [x] Put screenshots in README

- [x] Add a pull request template

- [x] Clean up the commented out code

If you guys think there are any other things left you can add it over here.

Edit: I think we can also display the full form of the personality type below the abbreviation for the personality. For instance, INTP will be Introvert-Intuitive-Thinker-Perceiving.

**Comment by sh-biswas** [comment]
Screenshots for README:

<img width="1440" alt="pic1" src="https://user-images.githubusercontent.com/51776663/98763145-3f581f00-238e-11eb-9c15-e59c3d898e7a.png">
<img width="1438" alt="pic2" src="https://user-images.githubusercontent.com/51776663/98763146-42eba600-238e-11eb-924e-2c45792281bb.png">
<img width="1440" alt="pic3" src="https://user-images.githubusercontent.com/51776663/98763149-441cd300-238e-11eb-983d-8b7d3ad5e877.png">
<img width="1440" alt="pic4" src="https://user-images.githubusercontent.com/51776663/98763154-467f2d00-238e-11eb-9e08-75589b52a507.png">
<img width="1439" alt="pic5" src="https://user-images.githubusercontent.com/51776663/98763157-4848f080-238e-11eb-9887-c463a77045c8.png">
