### ISSUE TITLE
ValueError: Cannot assign to variable tf_bert_model/bert/encoder/layer_._0/attention/self/query/kernel:0 due to variable shape (768, 12, 64) and value shape (768, 768) are incompatible

### ISSUE THREAD

**Issue by ShubhVats** [MLH-Fellowship/Social-BERTerfly#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rasikaburde10** [comment]
I am also getting the same issue, how to resolve it?

**Comment by ShubhVats** [comment]
I haven't been able to resolve it myself.
If you get any answers please let me know.

**Comment by V2dha** [comment]
It might be due to wrong version of tensorflow. The project uses Tensorflow==2.3.1 as mentioned in the requirements.txt. Try to install the same version of packages used in the project by running `pip install -r requirements.txt`

**Comment by ShubhVats** [comment]
Gee thanks👍
