### ISSUE TITLE
Google drive link provided not working

### ISSUE THREAD

**Issue by manjxt** [MLH-Fellowship/Social-BERTerfly#26]
the google drive link provided in the readme file is not working. Please provide a new link for the models

**Comment by vikas2dx** [comment]
the google drive link provided in the readme file is not working. Please provide a new link for the models

**Comment by mans00rahmed** [comment]
the google drive link provided in the readme file is not working. Please provide a new link for the models

**Comment by vikaskumar2703** [comment]
the link is working in my system

**Comment by pavansaiganesh** [comment]
the google drive link provided in the readme file is not working. Please provide a new link for the model weights
